name: Update Another Repository

on:
  push:
    branches:
      - development

jobs:
  update-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'Dilip'
          git config --global user.email 'diliptalks@gmail.com'

      - name: Update Another Repository
        run: |
          git clone https://github.com/learnerdilip/photo-upload-server
          cd webapp
          npm run build
          
          git clone https://github.com/learnerdilip/test
          cd test
          echo "Updated at $(date)" >> update.txt
          git add .
          git commit -m "Update from original repository"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}