name: Push to another repo

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Make changes
      run: echo "Hello, World!" > hello.txt

    - name: Commit and push
      uses: https://github.com/learnerdilip/test
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: username/other-repo
        branch: main
        directory: .
        commit_message: Commit from GitHub Actions